use std::collections::HashSet;
use std::path::PathBuf;
use std::sync::Arc;

use rmcp::{
    ErrorData as McpError, ServerHandler,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::*,
    tool, tool_handler, tool_router,
};
use schemars::JsonSchema;
use serde::Deserialize;
use serde_json::{Value, json};

use crate::config::Config;
use crate::{discovery, localdb, security, sql};

fn default_instance() -> String {
    "MSSQLLocalDB".to_string()
}

fn ok_json<T: serde::Serialize>(value: &T) -> Result<CallToolResult, McpError> {
    let text = serde_json::to_string(value)
        .map_err(|e| McpError::internal_error(format!("failed to serialize result: {e}"), None))?;
    Ok(CallToolResult::success(vec![ContentBlock::text(text)]))
}

fn confirmation_required(message: impl Into<String>) -> McpError {
    McpError::invalid_params(
        message.into(),
        Some(json!({"code": "CONFIRMATION_REQUIRED"})),
    )
}

fn localdb_error(e: localdb::LocalDbError) -> McpError {
    McpError::internal_error(e.to_string(), Some(json!({"code": "INSTANCE_NOT_FOUND"})))
}

fn sql_error(e: sql::SqlError) -> McpError {
    match e {
        sql::SqlError::ConfirmationRequired(batches) => McpError::invalid_params(
            "destructive action requires confirm=true",
            Some(json!({"code": "CONFIRMATION_REQUIRED", "destructive_batches": batches})),
        ),
        sql::SqlError::NotReadOnly => McpError::invalid_params(
            "statement is not read-only — use sql_execute_statement/sql_execute_script",
            Some(json!({"code": "NOT_READ_ONLY"})),
        ),
        other => McpError::internal_error(other.to_string(), Some(json!({"code": "SQL_ERROR"}))),
    }
}

fn security_error(e: security::SecurityError) -> McpError {
    match e {
        security::SecurityError::AllowlistEmpty => {
            McpError::invalid_params(e.to_string(), Some(json!({"code": "CONFIG_MISSING"})))
        }
        security::SecurityError::PathNotAllowed => McpError::invalid_params(
            "path outside the roots allowed in config.scan_allowlist",
            Some(json!({"code": "PATH_NOT_ALLOWED"})),
        ),
        security::SecurityError::Io(err) => McpError::internal_error(err.to_string(), None),
    }
}

/// Escapes single quotes for use inside a T-SQL string literal (`N'...'`).
/// Needed because paths and database names coming from the agent are
/// interpolated into DDL generated here (`db_attach`/`db_detach`).
fn escape_sql_literal(s: &str) -> String {
    s.replace('\'', "''")
}

/// Escapes `]` for use inside a bracketed T-SQL identifier (`[...]`).
fn escape_identifier(s: &str) -> String {
    s.replace(']', "]]")
}

#[derive(Debug, Deserialize, JsonSchema)]
struct InstanceArgs {
    instance: String,
}

#[derive(Debug, Deserialize, JsonSchema)]
struct CreateInstanceArgs {
    instance: String,
    version: Option<String>,
    start: Option<bool>,
}

#[derive(Debug, Deserialize, JsonSchema)]
struct StopInstanceArgs {
    instance: String,
    kill: Option<bool>,
}

#[derive(Debug, Deserialize, JsonSchema)]
struct DeleteInstanceArgs {
    instance: String,
    confirm: bool,
}

#[derive(Debug, Deserialize, JsonSchema)]
struct ExecuteScriptArgs {
    instance: Option<String>,
    database: String,
    script: String,
    confirm: Option<bool>,
}

#[derive(Debug, Deserialize, JsonSchema)]
struct ExecuteQueryArgs {
    instance: Option<String>,
    database: String,
    sql: String,
    max_rows: Option<usize>,
}

#[derive(Debug, Deserialize, JsonSchema)]
struct ExecuteStatementArgs {
    instance: Option<String>,
    database: String,
    sql: String,
    confirm: Option<bool>,
}

#[derive(Debug, Deserialize, JsonSchema)]
struct ScanFolderArgs {
    root: String,
    max_depth: Option<usize>,
}

#[derive(Debug, Deserialize, JsonSchema)]
struct AttachArgs {
    instance: Option<String>,
    mdf_path: String,
    database_name: Option<String>,
    ldf_path: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema)]
struct DetachArgs {
    instance: Option<String>,
    database: String,
    confirm: bool,
}

#[derive(Debug, Deserialize, JsonSchema)]
struct ListTablesArgs {
    instance: Option<String>,
    database: String,
    schema: Option<String>,
}

#[derive(Clone)]
pub struct McpServer {
    config: Arc<Config>,
    // Read by code generated by #[tool_handler]; the dead-code analyzer
    // doesn't see this usage through the macro expansion.
    #[allow(dead_code)]
    tool_router: ToolRouter<McpServer>,
}

#[tool_router]
impl McpServer {
    pub fn new(config: Config) -> Self {
        Self {
            config: Arc::new(config),
            tool_router: Self::tool_router(),
        }
    }

    // --- Group A: instance management -------------------------------------

    #[tool(description = "List all LocalDB instances registered on this machine")]
    async fn localdb_list_instances(&self) -> Result<CallToolResult, McpError> {
        let instances = localdb::list_instances().await.map_err(localdb_error)?;
        ok_json(&json!({ "instances": instances }))
    }

    #[tool(description = "List LocalDB versions installed on this machine")]
    async fn localdb_versions(&self) -> Result<CallToolResult, McpError> {
        let versions = localdb::versions().await.map_err(localdb_error)?;
        ok_json(&json!({ "versions": versions }))
    }

    #[tool(description = "Detail of a LocalDB instance: version, state, pipe name, owner")]
    async fn localdb_info(
        &self,
        Parameters(InstanceArgs { instance }): Parameters<InstanceArgs>,
    ) -> Result<CallToolResult, McpError> {
        let info = localdb::info(&instance).await.map_err(localdb_error)?;
        ok_json(&info)
    }

    #[tool(description = "Create a new LocalDB instance")]
    async fn localdb_create_instance(
        &self,
        Parameters(args): Parameters<CreateInstanceArgs>,
    ) -> Result<CallToolResult, McpError> {
        localdb::create(
            &args.instance,
            args.version.as_deref(),
            args.start.unwrap_or(false),
        )
        .await
        .map_err(localdb_error)?;
        ok_json(&json!({ "created": true, "instance": args.instance }))
    }

    #[tool(description = "Start a stopped LocalDB instance")]
    async fn localdb_start_instance(
        &self,
        Parameters(InstanceArgs { instance }): Parameters<InstanceArgs>,
    ) -> Result<CallToolResult, McpError> {
        let pipe_name = localdb::start(&instance).await.map_err(localdb_error)?;
        ok_json(&json!({ "started": true, "pipe_name": pipe_name }))
    }

    #[tool(description = "Stop a running LocalDB instance")]
    async fn localdb_stop_instance(
        &self,
        Parameters(args): Parameters<StopInstanceArgs>,
    ) -> Result<CallToolResult, McpError> {
        localdb::stop(&args.instance, args.kill.unwrap_or(false))
            .await
            .map_err(localdb_error)?;
        ok_json(&json!({ "stopped": true }))
    }

    #[tool(
        description = "Delete a LocalDB instance (does not delete attached database files). Destructive — requires confirm=true"
    )]
    async fn localdb_delete_instance(
        &self,
        Parameters(args): Parameters<DeleteInstanceArgs>,
    ) -> Result<CallToolResult, McpError> {
        if !args.confirm {
            return Err(confirmation_required(
                "deleting the instance requires confirm=true",
            ));
        }
        localdb::delete(&args.instance)
            .await
            .map_err(localdb_error)?;
        ok_json(&json!({ "deleted": true }))
    }

    // --- Group B: script/SQL channel --------------------------------------

    #[tool(
        description = "Run a multi-batch T-SQL script (GO on its own line as separator) in the same session. Destructive batch requires confirm=true"
    )]
    async fn sql_execute_script(
        &self,
        Parameters(args): Parameters<ExecuteScriptArgs>,
    ) -> Result<CallToolResult, McpError> {
        let instance = args.instance.unwrap_or_else(default_instance);
        let pipe_name = localdb::ensure_running(&instance)
            .await
            .map_err(localdb_error)?;
        let batches = sql::execute_script(
            &pipe_name,
            &args.database,
            &args.script,
            args.confirm.unwrap_or(false),
        )
        .await
        .map_err(sql_error)?;
        ok_json(&json!({ "batches": batches }))
    }

    #[tool(description = "Run a SELECT (read-only) and return the rows as JSON")]
    async fn sql_execute_query(
        &self,
        Parameters(args): Parameters<ExecuteQueryArgs>,
    ) -> Result<CallToolResult, McpError> {
        let instance = args.instance.unwrap_or_else(default_instance);
        let pipe_name = localdb::ensure_running(&instance)
            .await
            .map_err(localdb_error)?;
        let max_rows = args.max_rows.unwrap_or(self.config.default_max_rows);
        let result = sql::execute_query(&pipe_name, &args.database, &args.sql, max_rows)
            .await
            .map_err(sql_error)?;
        ok_json(&result)
    }

    #[tool(description = "Run a single DML/DDL statement. Destructive requires confirm=true")]
    async fn sql_execute_statement(
        &self,
        Parameters(args): Parameters<ExecuteStatementArgs>,
    ) -> Result<CallToolResult, McpError> {
        let instance = args.instance.unwrap_or_else(default_instance);
        let pipe_name = localdb::ensure_running(&instance)
            .await
            .map_err(localdb_error)?;
        let result = sql::execute_statement(
            &pipe_name,
            &args.database,
            &args.sql,
            args.confirm.unwrap_or(false),
        )
        .await
        .map_err(sql_error)?;
        ok_json(&result)
    }

    // --- Group C: discovery and metadata -----------------------------------

    #[tool(
        description = "Scan a folder for loose .mdf/.ldf files. Restricted to the roots in config.scan_allowlist"
    )]
    async fn db_scan_folder(
        &self,
        Parameters(args): Parameters<ScanFolderArgs>,
    ) -> Result<CallToolResult, McpError> {
        let root = PathBuf::from(&args.root);
        let validated =
            security::validate_path(&root, &self.config.scan_allowlist).map_err(security_error)?;
        let max_depth = args.max_depth.unwrap_or(self.config.scan_max_depth);

        let found = discovery::scan_folder(&validated, max_depth, &HashSet::new());

        ok_json(&json!({ "found": found }))
    }

    #[tool(
        description = "Attach a loose .mdf (found via db_scan_folder) as a database on the instance"
    )]
    async fn db_attach(
        &self,
        Parameters(args): Parameters<AttachArgs>,
    ) -> Result<CallToolResult, McpError> {
        let mdf_path = PathBuf::from(&args.mdf_path);
        let validated_mdf = security::validate_path(&mdf_path, &self.config.scan_allowlist)
            .map_err(security_error)?;

        let instance = args.instance.unwrap_or_else(default_instance);
        let pipe_name = localdb::ensure_running(&instance)
            .await
            .map_err(localdb_error)?;

        let database_name = args.database_name.unwrap_or_else(|| {
            validated_mdf
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("attached_db")
                .to_string()
        });

        let mut files = format!(
            "(FILENAME = N'{}')",
            escape_sql_literal(&validated_mdf.to_string_lossy())
        );

        if let Some(ldf) = &args.ldf_path {
            let validated_ldf =
                security::validate_path(&PathBuf::from(ldf), &self.config.scan_allowlist)
                    .map_err(security_error)?;
            files.push_str(&format!(
                ", (FILENAME = N'{}')",
                escape_sql_literal(&validated_ldf.to_string_lossy())
            ));
        }

        let statement = format!(
            "CREATE DATABASE [{}] ON {} FOR ATTACH",
            escape_identifier(&database_name),
            files
        );

        // CREATE DATABASE ... FOR ATTACH is additive (security::classify
        // already treats it as ReadOnly), so confirm=false is safe here.
        sql::execute_statement(&pipe_name, "master", &statement, false)
            .await
            .map_err(sql_error)?;

        ok_json(&json!({ "attached": true, "database": database_name }))
    }

    #[tool(
        description = "Detach a database from the instance (sp_detach_db). Destructive — requires confirm=true"
    )]
    async fn db_detach(
        &self,
        Parameters(args): Parameters<DetachArgs>,
    ) -> Result<CallToolResult, McpError> {
        if !args.confirm {
            return Err(confirmation_required(
                "detaching a database requires confirm=true",
            ));
        }

        let instance = args.instance.unwrap_or_else(default_instance);
        let pipe_name = localdb::ensure_running(&instance)
            .await
            .map_err(localdb_error)?;

        let statement = format!(
            "EXEC sp_detach_db N'{}'",
            escape_sql_literal(&args.database)
        );
        sql::execute_statement(&pipe_name, "master", &statement, true)
            .await
            .map_err(sql_error)?;

        ok_json(&json!({ "detached": true }))
    }

    #[tool(description = "List tables in the database (via INFORMATION_SCHEMA)")]
    async fn db_list_tables(
        &self,
        Parameters(args): Parameters<ListTablesArgs>,
    ) -> Result<CallToolResult, McpError> {
        let instance = args.instance.unwrap_or_else(default_instance);
        let pipe_name = localdb::ensure_running(&instance)
            .await
            .map_err(localdb_error)?;

        let sql_text = match &args.schema {
            Some(schema) => format!(
                "SELECT TABLE_SCHEMA AS [schema], TABLE_NAME AS [name] FROM INFORMATION_SCHEMA.TABLES \
                 WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = N'{}' ORDER BY TABLE_SCHEMA, TABLE_NAME",
                escape_sql_literal(schema)
            ),
            None => "SELECT TABLE_SCHEMA AS [schema], TABLE_NAME AS [name] FROM INFORMATION_SCHEMA.TABLES \
                      WHERE TABLE_TYPE = 'BASE TABLE' ORDER BY TABLE_SCHEMA, TABLE_NAME"
                .to_string(),
        };

        let result = sql::execute_query(&pipe_name, &args.database, &sql_text, 10_000)
            .await
            .map_err(sql_error)?;

        let tables: Vec<Value> = result
            .rows
            .iter()
            .map(|row| {
                json!({
                    "schema": row.first().cloned().unwrap_or(Value::Null),
                    "name": row.get(1).cloned().unwrap_or(Value::Null),
                    "row_count_estimate": Value::Null,
                })
            })
            .collect();

        ok_json(&json!({ "tables": tables }))
    }
}

#[tool_handler]
impl ServerHandler for McpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::from_build_env())
            .with_protocol_version(ProtocolVersion::V_2024_11_05)
            .with_instructions(
                "MCP server for SQL Server Express LocalDB on Windows. Manages instances \
                 (localdb_*), runs T-SQL (sql_*), and discovers/attaches loose databases in \
                 folders (db_*). Every destructive action requires confirm=true."
                    .to_string(),
            )
    }
}
